name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main     # Triggers build on push to the "main" branch

permissions:
  contents: write # Required for committing files to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy static files to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The output folder of "npm run build"
          branch: gh-pages # The target branch that holds deployed site content
